Add /products endpoint
alexeyzab/ballast pull request #8
Opened 2016-11-19 19:42 UTC by alexeyzab

This adds the necessary functionality to get back a list of
products.

For some reason the documentation for this endpoint is more
sparse than before. There is no model schema so certain
JSON objects are impossible to understand.

It was also not specified which fields might return "null",
I've had to test and see manually.

There is one point of interest over here:
```
data ProductsWrapper = PwBaseProduct BaseProductResource
  | PwMarketingInsert MarketingInsertResource  
  | PwVirtualKit VirtualKitResource
  | PwKit KitResource
  deriving (Eq, Show)

instance FromJSON ProductsWrapper where
  parseJSON (Object v) = piwValue
    where
      isBaseProduct     = HM.lookup "classification" v == Just "baseProduct"
      isMarketingInsert = HM.lookup "classification" v == Just "marketingInsert"
      isVirtualKit      = HM.lookup "classification" v == Just "virtualKit"
      isKit             = HM.lookup "classification" v == Just "kit"
      piwValue          = parseProductsWrapper isBaseProduct isMarketingInsert isVirtualKit isKit v
  parseJSON _ = mempty

parseProductsWrapper :: Bool -> Bool -> Bool -> Bool -> Object -> Parser ProductsWrapper
parseProductsWrapper isBaseProduct isMarketingInsert isVirtualKit isKit value
  | isBaseProduct     = PwBaseProduct     <$> parseBaseProduct value
  | isMarketingInsert = PwMarketingInsert <$> parseMarketingInsert value
  | isVirtualKit      = PwVirtualKit      <$> parseVirtualKit value
  | isKit             = PwKit             <$> parseKit value
  | otherwise         = PwBaseProduct     <$> parseBaseProduct value
```

Products include 4 possible classifications such as `baseProduct`, `marketingInsert`, `virtualKit`, `kit`. They get returned together in the same array. So here I am checking the `classification` field first and then parse the object based on that. I've modeled it after your [blogpost](http://bitemyapp.com/posts/2014-04-17-parsing-nondeterministic-data-with-aeson-and-sum-types.html) I've stumbled upon.

2016-12-09 19:34 UTC, bitemyapp commented
Had a few comments, otherwise, once those are resolved I think this is good to go. Great work! This seemed pretty laborious :open_mouth:

2016-12-09 19:39 UTC, alexeyzab commented
@bitemyapp Thanks! I'll write down a few things that bother me a bit with this endpoint later on too. There were a few parts where I wasn't too sure about my approach.

2016-12-09 20:49 UTC, bitemyapp requested changes

2016-12-09 23:51 UTC, bitemyapp approved these changes

2016-12-10 00:01 UTC, alexeyzab commented
@bitemyapp I've replaced `error` with `fail` everywhere.

Now here are a few things that bother me:

1. Sending date as Text:
```
InsertAfterDate "3016-02-15T13:04:26-05:00"
InsertBeforeDate "3016-02-15T13:04:26-05:00"
```

Shipwire expects a String of ISO8601 format like this: `"2014-05-27T00:00:00-07:00"`

I feel like it might be wrong to send a date like that. But `formatISO8601` function from `iso8601-time` package doesn't format the time the way Shipwire needs it to be. What would be a good approach here? Make a helper function that takes a `UTCTime`, puts it through `formatISO8601` and then edits the output string?

2. ProductErrors:
```
-- | There is a separate error class for /products endpoint apparently.
-- It returns back JSON with field names as object names and
-- details hidden inside that object. It is not specified anywhere what those might be.
-- So for now I treat them as an Object.
-- There must be a better way of dealing with it.
-- E.g.:
--   "errors": {
--    "myMarketingInsert": {
--      "code": "productSubmitFailed",
--      "externalId": null,
--      "id": null,
--      "sku": "myMarketingInsert",
--      "message": {
--        "sku": {
--          "stringLengthTooLong": "SKU must be between 1 and 16 characters"
--        },
--        "masterCase_sku": {
--          "stringLengthTooLong": "Master case SKU must be between 1 and 16 characters"
--        },
--      },
--      "type": {
--        "sku": {
--          "stringLengthTooLong": "error"
--        },
--        "masterCase_sku": {
--          "stringLengthTooLong": "error"
--        },
--      }
--    }
--  }

newtype ProductError = ProductError
  { unProductError :: Object
  } deriving (Eq, Show, FromJSON)
```

What do you think about this? I am not sure if treating it just as an `Object` is good enough.

3. You might've noticed that the second CI test failed just now. That's because I haven't yet implemented a function to delete products from the catalog. Once that's there, I'll add it as a cleanup step for the tests, that way we would be able to rerun them.

2016-12-10 00:14 UTC, bitemyapp commented
>I feel like it might be wrong to send a date like that. But formatISO8601 function from iso8601-time package doesn't format the time the way Shipwire needs it to be. What would be a good approach here? Make a helper function that takes a UTCTime, puts it through formatISO8601 and then edits the output string?

Close, but don't edit strings. Write a function that picks apart the components of UTCTime and generates the Text value directly. I can make a small demonstration on screenshare if you like.

>What do you think about this? I am not sure if treating it just as an Object is good enough.

It's fine for now. Bloodhound is a couple years old and we still haven't really bothered to lift the errors into the types.

Re: #3 - that's fine, just let me know when the PR is ready.

2016-12-10 00:29 UTC, alexeyzab commented
@bitemyapp Gotcha. Yeah, a demonstration would be nice. What time works for you?

2016-12-10 00:30 UTC, bitemyapp commented
@alexeyzab can-do in a half hour or hour, soon as I get Papu to stop barking at shadows. Otherwise, sometime this weekend.

2016-12-10 00:31 UTC, alexeyzab commented
@bitemyapp Sure, sounds good. Papu has switched from stuffed toys to shadows, huh.

2016-12-10 00:32 UTC, bitemyapp commented
@alexeyzab he thinks alert-barking at everything is his job

2016-12-10 00:33 UTC, alexeyzab commented
@bitemyapp Well, I mean...

2017-01-09 06:54 UTC, alexeyzab commented
@bitemyapp Hey Chris! This endpoint should be all done now.

2017-01-10 05:13 UTC, merged

2017-01-10 05:14 UTC, bitemyapp commented
@alexeyzab amazing work man. That was so much to review O_O